version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
     - RAILS_ENV=production